version: '3.8'

services:

  webserver:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./infra/nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/public:/var/www/public

  core:
    build:
      context: ./core
      dockerfile: ../infra/node/Dockerfile
      target: dependencies
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - /var/www/app/node_modules
    depends_on:
      - mariadb
    command: yarn start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/node/Dockerfile
      target: dependencies
    ports:
      - "3000:3000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - /var/www/app/node_modules
    command: yarn dev
    
  mariadb:
    image: mariadb
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD_ROOT}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      # - ./infra/mysql/my.cnf:/etc/mysql/my.cnf
      - ./infra/database/.docker/dbdata:/var/lib/mysql
      # - ./infra/database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - db-network

  keycloak:
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_HTTP_PORT=80
      - DEBUG=true
      # - KEYCLOAK_USER=admin
      # - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_HOSTNAME=localhost
    build:
      context: infra/keycloak
      dockerfile: ./Dockerfile
    volumes:
      # - ./infra/keycloak/themes:/opt/jboss/keycloak/themes
      - ./infra/keycloak/configuration:/opt/jboss/keycloak/standalone/configuration

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD_ROOT}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    networks:
      - db-network
    depends_on:
      - mariadb
  # database-keycloak:
  #   volumes:
  #     - ./infra/keycloak/mysql/keycloak-dump.sql:/docker-entrypoint-initdb.d/dump.sql
