version: '3.8'

services:

  webserver:
    tty: true
    depends_on:
      - main-api
    networks:
      - app-network
  
  frontend:
    env_file:
      - ./front/.env
    volumes:
      - ./front:/var/www/app
    networks:
      - app-network

  core:
    env_file:
      - ./core/.env
    volumes:
      - ./core:/var/www/app
    networks:
      - app-network
      - db-network

  db-keycloak:
      image: postgres:13.7
      volumes:
        - ./infra/keycloak/.dbata:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloakDB
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: root
      networks:
        - keycloak-db-network

  keycloak:
      build:
        context: ./infra/keycloak
      environment:
        KC_DB: postgres
        KC_DB_URL: 'jdbc:postgresql://db-keycloak/keycloakDB'
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: root
        KC_DB_SCHEMA: public
        KC_HOSTNAME: "localhost"
        KC_HOSTNAME_STRICT_HTTPS: 'false'
        KC_HOSTNAME_STRICT: 'true'
        KC_PROXY: passthrough
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      depends_on:
        - db-keycloak
      networks:
        - keycloak-db-network
        - app-network
      ports:
        - 8080:8080

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge
  keycloak-db-network:
    driver: bridge